version: "3.9"
services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd