version: "3.3"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "44380:44380"
    depends_on:
      - database
  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume: