version: "3.3"
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "44380:44380"
    extra_hosts:
      wding.org: 127.0.0.1
    depends_on:
      - database
  database:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: passw0rd
    volumes:
      - wding-db-volume:/var/lib/mysql
volumes:
  wding-db-volume:
    external: true